version: '3.3'

services:
  service-php:
    image: saadbarhrouj/php_laravel_angular:SE
    container_name: container_php
    depends_on:
      - db
    volumes:
      - ./application:/var/www/html/
    ports:
      - "8083:80"

  db:
    container_name: container_mysql
    image: saadbarhrouj/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - "6033:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: saadbarhrouj/phpmyadmin:latest
    container_name: container_phpmyadmin
    depends_on:
      - db
    ports:
      - "8088:80"
    environment:
      PMA_HOST: db
      PMA_USER: 
      PMA_PASSWORD:

volumes:
  db_data:
