version: '3.3'
services:
  service-php:
    container_name: php_container
   image: saadbarhrouj/php:8.1.2-apache
    depends_on:
      - db-service
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80
  db-service:
    container_name: mysq_container
    image:saadbarhrouj/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - 6033:3306
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: saadbarhrouj/phpmyadmin:latest
    container_name: phpmyadmin_container
    links:
      - db-service
    ports:
      - 8081:80
    environment:
      PMA_HOST:db-service
      PMA_USER: 
      PMA_PASSWORD:

volumes:
  db_data:
